/**
 * The seed exercise library and routines, encoding the hunter's actual training
 * week rather than a published programme.
 *
 * Original spellings from the brief are kept as `aliases` so search finds each
 * exercise by the name it is actually called. The engine applies progressive
 * overload to these movements; it does not replace them with something else.
 *
 * Increments follow the brief: upper-body isolation 1.25 to 2.5 kg, upper
 * compound 2.5 kg, lower compound 5 kg, and cables and machines one pin step.
 */
import type { Exercise, Routine } from '../domain/types'

/** One pin step on the cable stacks and most selectorised machines. */
const PIN_STEP = 2.5

export const SEED_EXERCISES: readonly Exercise[] = [
  /* ---------------- Monday: chest, shoulders, triceps ---------------- */
  {
    id: 'incline-barbell-press',
    name: 'Incline Barbell Press',
    aliases: ['Incline Barbel Press', 'Incline Bench Press', 'Incline Press'],
    pattern: 'horizontal_push',
    primaryMuscles: ['chest'],
    secondaryMuscles: ['front_delts', 'triceps'],
    equipment: ['barbell', 'bench'],
    unit: 'kg',
    increment: 2.5,
    repRange: [5, 8],
    standardLift: 'incline_bench',
    cue: 'Elbows about 45 degrees from the torso. Bar to the upper chest, not the throat.',
    usesBodyweight: false,
    bodyweightFactor: 1,
    role: 'prescribed',
  },
  {
    id: 'machine-shoulder-press',
    name: 'Machine Shoulder Press',
    aliases: ['Shoulder Press Machine'],
    pattern: 'vertical_push',
    primaryMuscles: ['front_delts'],
    secondaryMuscles: ['side_delts', 'triceps'],
    equipment: ['machine'],
    unit: 'kg',
    increment: PIN_STEP,
    repRange: [8, 12],
    cue: 'Do not lock out hard at the top. Keep the ribs down.',
    usesBodyweight: false,
    bodyweightFactor: 1,
    role: 'prescribed',
  },
  {
    id: 'skullcrusher',
    name: 'Skullcrusher',
    aliases: ['Skull Crusher', 'Lying Triceps Extension'],
    pattern: 'isolation',
    primaryMuscles: ['triceps'],
    secondaryMuscles: [],
    equipment: ['ez_bar', 'bench'],
    unit: 'kg',
    increment: 1.25,
    repRange: [8, 12],
    cue: 'Elbows stay pointed at the ceiling. Only the forearm moves.',
    usesBodyweight: false,
    bodyweightFactor: 1,
    role: 'prescribed',
  },
  {
    id: 'cable-fly',
    name: 'Cable Fly',
    aliases: ['Cable Flye', 'Cable Crossover'],
    pattern: 'isolation',
    primaryMuscles: ['chest'],
    secondaryMuscles: ['front_delts'],
    equipment: ['cable'],
    unit: 'kg',
    increment: PIN_STEP,
    repRange: [10, 15],
    cue: 'Slight elbow bend held constant. Squeeze at the midline, do not clap.',
    usesBodyweight: false,
    bodyweightFactor: 1,
    role: 'prescribed',
  },
  {
    id: 'machine-lateral-raise',
    name: 'Machine Lateral Raise',
    aliases: ['Lateral Raise Machine', 'Machine Side Raise'],
    pattern: 'isolation',
    primaryMuscles: ['side_delts'],
    secondaryMuscles: [],
    equipment: ['machine'],
    unit: 'kg',
    increment: PIN_STEP,
    repRange: [12, 20],
    cue: 'Lead with the elbow. Stop at shoulder height.',
    usesBodyweight: false,
    bodyweightFactor: 1,
    role: 'prescribed',
  },
  {
    id: 'front-raises',
    name: 'Front Raises',
    aliases: ['Front Raise'],
    pattern: 'isolation',
    primaryMuscles: ['front_delts'],
    secondaryMuscles: [],
    equipment: ['dumbbell'],
    unit: 'kg',
    increment: 1.25,
    repRange: [12, 15],
    cue: 'The pressing already trains this head hard. Keep the load honest and the swing out of it.',
    usesBodyweight: false,
    bodyweightFactor: 1,
    role: 'prescribed',
  },
  {
    id: 'diamond-pushups',
    name: 'Diamond Pushups',
    aliases: ['Dimond Pushups', 'Diamond Push-ups', 'Close-grip Pushups'],
    pattern: 'horizontal_push',
    primaryMuscles: ['triceps'],
    secondaryMuscles: ['chest', 'front_delts'],
    equipment: ['bodyweight'],
    unit: 'reps',
    increment: 0,
    repRange: [8, 20],
    progressionLadder: ['incline-pushups', 'pushups', 'diamond-pushups'],
    cue: 'Hands together under the sternum. Elbows brush the ribs.',
    usesBodyweight: true,
    // Reasoned from segment mass, not measured — see docs/TODO.md's Exercise substitution entry (commit 5ce8d44).
    bodyweightFactor: 0.66,
    role: 'prescribed',
  },

  /* ---------------- Tuesday: back and biceps ---------------- */
  {
    id: 'one-arm-cable-lat-pulldown',
    name: '1-Arm Cable Lat Pulldown',
    aliases: ['1-Arm Cabel Lat Pulldown', 'Single Arm Lat Pulldown', 'One Arm Pulldown'],
    pattern: 'vertical_pull',
    primaryMuscles: ['lats'],
    secondaryMuscles: ['biceps', 'upper_back'],
    equipment: ['cable'],
    unit: 'kg',
    increment: PIN_STEP,
    repRange: [8, 12],
    cue: 'Let the shoulder rise at the top, then drive the elbow down and back.',
    usesBodyweight: false,
    bodyweightFactor: 1,
    role: 'prescribed',
  },
  {
    id: 'pull-ups',
    name: 'Pull-ups',
    // 'Chin-ups' is deliberately not an alias here — commit 4 seeds it as its
    // own fallback exercise with biceps as the primary mover, which an
    // overhand Pull-up does not represent. See commit 5d33216.
    aliases: ['Pullups', 'Pull Ups'],
    pattern: 'vertical_pull',
    primaryMuscles: ['lats'],
    secondaryMuscles: ['biceps', 'upper_back', 'grip'],
    equipment: ['pullup_bar', 'bodyweight'],
    unit: 'reps',
    increment: 0,
    repRange: [5, 12],
    standardLift: 'pullup',
    cue: 'Full hang at the bottom. Chest to the bar, no kipping.',
    usesBodyweight: true,
    // Reasoned, not measured — a dead hang moves nearly all of it. See docs/TODO.md's Exercise substitution entry (commit 5ce8d44).
    bodyweightFactor: 0.95,
    role: 'prescribed',
  },
  {
    id: 'dumbbell-row',
    name: 'Dumbbell Row',
    aliases: ['Dumble Row', 'One Arm Row', 'DB Row'],
    pattern: 'horizontal_pull',
    primaryMuscles: ['upper_back'],
    secondaryMuscles: ['lats', 'biceps', 'grip'],
    equipment: ['dumbbell', 'bench'],
    unit: 'kg',
    increment: 2.5,
    repRange: [8, 12],
    cue: 'Pull to the hip, not the armpit. Keep the torso still.',
    usesBodyweight: false,
    bodyweightFactor: 1,
    role: 'prescribed',
  },
  {
    id: 'cable-shrug',
    name: 'Cable Shrug',
    // The hunter calls this a "Cable Shrug-in": standing at a low pulley holding
    // a straight bar at hip height and shrugging.
    aliases: ['Cable Shrug-in', 'Cable Shrug In', 'Low Pulley Shrug'],
    pattern: 'isolation',
    primaryMuscles: ['traps'],
    secondaryMuscles: ['grip', 'upper_back'],
    equipment: ['cable'],
    unit: 'kg',
    increment: PIN_STEP,
    repRange: [10, 15],
    cue: 'Straight up and down. No rolling — rolling the shoulders adds nothing and grinds the joint.',
    usesBodyweight: false,
    bodyweightFactor: 1,
    role: 'prescribed',
  },
  {
    id: 'machine-reverse-fly',
    name: 'Machine Reverse Fly',
    aliases: ['Reverse Fly Machine', 'Rear Delt Machine', 'Pec Deck Reverse'],
    pattern: 'isolation',
    primaryMuscles: ['rear_delts'],
    secondaryMuscles: ['upper_back'],
    equipment: ['machine'],
    unit: 'kg',
    increment: PIN_STEP,
    repRange: [12, 20],
    cue: 'Arms nearly straight. Think about spreading the hands apart, not squeezing the blades.',
    usesBodyweight: false,
    bodyweightFactor: 1,
    role: 'prescribed',
  },
  {
    id: 'cable-bicep-curl',
    name: 'Cable Bicep Curl',
    aliases: ['Cabel Bicep Curl', 'Cable Curl'],
    pattern: 'isolation',
    primaryMuscles: ['biceps'],
    secondaryMuscles: ['forearms'],
    equipment: ['cable'],
    unit: 'kg',
    increment: PIN_STEP,
    repRange: [10, 15],
    cue: 'Elbows pinned to the sides. The cable keeps tension at the top, so use it.',
    usesBodyweight: false,
    bodyweightFactor: 1,
    role: 'prescribed',
  },

  /* ---------------- Wednesday: abs and biceps ---------------- */
  {
    id: 'machine-preacher-curl',
    name: 'Machine Preacher Curls',
    aliases: ['Preacher Curl Machine', 'Machine Preacher Curl'],
    pattern: 'isolation',
    primaryMuscles: ['biceps'],
    secondaryMuscles: [],
    equipment: ['machine'],
    unit: 'kg',
    increment: PIN_STEP,
    repRange: [10, 15],
    cue: 'The pad removes the cheat. Do not fight it by lifting the elbows.',
    usesBodyweight: false,
    bodyweightFactor: 1,
    role: 'prescribed',
  },
  {
    id: 'strict-curl',
    name: 'Strict Curls',
    aliases: ['Strict Curl', 'Barbell Strict Curl'],
    pattern: 'isolation',
    primaryMuscles: ['biceps'],
    secondaryMuscles: ['forearms'],
    equipment: ['barbell'],
    unit: 'kg',
    increment: 1.25,
    repRange: [6, 10],
    cue: 'Back against a wall if there is one. No hip drive at all.',
    usesBodyweight: false,
    bodyweightFactor: 1,
    role: 'prescribed',
  },
  {
    id: 'leg-raises',
    name: 'Leg Raises',
    aliases: ['Lying Leg Raise', 'Leg Raise'],
    pattern: 'core',
    primaryMuscles: ['abs'],
    secondaryMuscles: ['obliques'],
    equipment: ['bodyweight'],
    unit: 'reps',
    increment: 0,
    repRange: [12, 20],
    progressionLadder: ['leg-raises', 'hanging-leg-raises'],
    cue: 'Press the lower back into the floor. Stop before it arches.',
    usesBodyweight: true,
    // Reasoned from segment mass, not measured — legs only. See docs/TODO.md's Exercise substitution entry (commit 5ce8d44).
    bodyweightFactor: 0.3,
    role: 'prescribed',
  },
  {
    id: 'machine-abs-crunch',
    name: 'Machine Abs Crunch',
    aliases: ['Ab Crunch Machine', 'Machine Crunch'],
    pattern: 'core',
    primaryMuscles: ['abs'],
    secondaryMuscles: [],
    equipment: ['machine'],
    unit: 'kg',
    increment: PIN_STEP,
    repRange: [10, 15],
    cue: 'Shorten the distance between ribs and hips. It is a curl, not a hip fold.',
    usesBodyweight: false,
    bodyweightFactor: 1,
    role: 'prescribed',
  },
  {
    id: 'cable-crunch',
    name: 'Cable Crunch',
    aliases: ['Kneeling Cable Crunch', 'Rope Crunch'],
    pattern: 'core',
    primaryMuscles: ['abs'],
    secondaryMuscles: ['obliques'],
    equipment: ['cable'],
    unit: 'kg',
    increment: PIN_STEP,
    repRange: [10, 15],
    cue: 'Hips stay where they are. Pull the elbows toward the knees with the abs.',
    usesBodyweight: false,
    bodyweightFactor: 1,
    role: 'prescribed',
  },

  /* ---------------- Thursday: chest, shoulders, triceps, supersetted ---------------- */
  {
    id: 'incline-pushups',
    name: 'Incline Pushups',
    aliases: ['Incline Push-ups', 'Hands-elevated Pushups'],
    pattern: 'horizontal_push',
    primaryMuscles: ['chest'],
    secondaryMuscles: ['front_delts', 'triceps'],
    equipment: ['bodyweight', 'bench'],
    unit: 'reps',
    increment: 0,
    repRange: [10, 20],
    progressionLadder: ['incline-pushups', 'pushups', 'diamond-pushups'],
    cue: 'The higher the hands, the easier it is. Lower the hands as this gets easy.',
    usesBodyweight: true,
    // Reasoned, not measured, and the honest weak spot: this genuinely varies
    // with bench height, and one number is wrong at both ends. See docs/TODO.md's Exercise substitution entry (commit 5ce8d44).
    bodyweightFactor: 0.5,
    role: 'prescribed',
  },
  {
    id: 'pike-pushups',
    name: 'Pike Pushups',
    aliases: ['Pike Push-ups'],
    pattern: 'vertical_push',
    primaryMuscles: ['front_delts'],
    secondaryMuscles: ['triceps', 'chest'],
    equipment: ['bodyweight'],
    unit: 'reps',
    increment: 0,
    repRange: [8, 15],
    // Its own ladder, not the horizontal_push line: front_delts via a vertical
    // press is a different pattern and muscle than a pushup. Nothing else in
    // the library is a bodyweight vertical_push progression yet, so this rung
    // is alone until commit 4 seeds a fallback for that gap.
    progressionLadder: ['pike-pushups'],
    cue: 'Hips high, head travels between the hands. This one is a shoulder press.',
    usesBodyweight: true,
    // Reasoned, not measured — torso vertical, most of the load on the shoulders. See docs/TODO.md's Exercise substitution entry (commit 5ce8d44).
    bodyweightFactor: 0.7,
    role: 'prescribed',
  },
  {
    id: 'cable-chest-press-mid',
    name: 'Cable Chest Press (mid chest)',
    aliases: ['Cable Press Mid', 'Cable Chest Press'],
    pattern: 'horizontal_push',
    primaryMuscles: ['chest'],
    secondaryMuscles: ['front_delts', 'triceps'],
    equipment: ['cable'],
    unit: 'kg',
    increment: PIN_STEP,
    repRange: [10, 15],
    cue: 'Pulleys at chest height. Press straight out and squeeze at the midline.',
    usesBodyweight: false,
    bodyweightFactor: 1,
    role: 'prescribed',
  },
  {
    id: 'cable-chest-press-low',
    name: 'Cable Chest Press (lower chest)',
    aliases: ['Cable Press Low', 'High-to-low Cable Press'],
    pattern: 'horizontal_push',
    primaryMuscles: ['chest'],
    secondaryMuscles: ['front_delts', 'triceps'],
    equipment: ['cable'],
    unit: 'kg',
    increment: PIN_STEP,
    repRange: [10, 15],
    cue: 'Pulleys high, press down and in toward the hips.',
    usesBodyweight: false,
    bodyweightFactor: 1,
    role: 'prescribed',
  },
  {
    id: 'cable-chest-press-high',
    name: 'Cable Chest Press (upper chest)',
    aliases: ['Cable Press High', 'Low-to-high Cable Press'],
    pattern: 'horizontal_push',
    primaryMuscles: ['chest'],
    secondaryMuscles: ['front_delts', 'triceps'],
    equipment: ['cable'],
    unit: 'kg',
    increment: PIN_STEP,
    repRange: [10, 15],
    cue: 'Pulleys low, press up and in toward the collarbones.',
    usesBodyweight: false,
    bodyweightFactor: 1,
    role: 'prescribed',
  },
  {
    id: 'tricep-overhead-extension',
    name: 'Tricep Overhead Extension',
    aliases: ['Tricep Overhead Extention', 'Overhead Tricep Extension'],
    pattern: 'isolation',
    primaryMuscles: ['triceps'],
    secondaryMuscles: [],
    equipment: ['cable'],
    unit: 'kg',
    increment: PIN_STEP,
    repRange: [10, 15],
    cue: 'Upper arms stay beside the ears. The stretch at the bottom is the point.',
    usesBodyweight: false,
    bodyweightFactor: 1,
    role: 'prescribed',
  },

  /* ---------------- Friday: legs ---------------- */
  {
    id: 'barbell-squat',
    name: 'Barbell Squats',
    aliases: ['Barbell Squat', 'Back Squat', 'Squat'],
    pattern: 'squat',
    primaryMuscles: ['quads'],
    secondaryMuscles: ['glutes', 'lower_back', 'hamstrings'],
    equipment: ['barbell'],
    unit: 'kg',
    increment: 5,
    repRange: [5, 8],
    standardLift: 'squat',
    cue: 'Knees track over the toes. Depth first, load second.',
    usesBodyweight: false,
    bodyweightFactor: 1,
    role: 'prescribed',
  },
  {
    id: 'leg-press',
    name: 'Leg Press',
    aliases: ['Machine Leg Press'],
    pattern: 'squat',
    primaryMuscles: ['quads'],
    secondaryMuscles: ['glutes'],
    equipment: ['machine'],
    unit: 'kg',
    increment: 5,
    repRange: [10, 15],
    cue: 'Do not let the lower back round off the pad at the bottom.',
    usesBodyweight: false,
    bodyweightFactor: 1,
    role: 'prescribed',
  },
  {
    id: 'hamstring-curl',
    name: 'Hamstring Curl',
    aliases: ['Leg Curl', 'Lying Leg Curl', 'Seated Leg Curl'],
    pattern: 'isolation',
    primaryMuscles: ['hamstrings'],
    secondaryMuscles: ['calves'],
    equipment: ['machine'],
    unit: 'kg',
    increment: PIN_STEP,
    repRange: [10, 15],
    cue: 'The only hamstring work in the week. Control the lowering.',
    usesBodyweight: false,
    bodyweightFactor: 1,
    role: 'prescribed',
  },
  {
    id: 'leg-extension',
    name: 'Leg Extension',
    aliases: ['Quad Extension'],
    pattern: 'isolation',
    primaryMuscles: ['quads'],
    secondaryMuscles: [],
    equipment: ['machine'],
    unit: 'kg',
    increment: PIN_STEP,
    repRange: [12, 15],
    cue: 'Pause at the top for a beat rather than swinging through.',
    usesBodyweight: false,
    bodyweightFactor: 1,
    role: 'prescribed',
  },
  {
    id: 'barbell-calf-raise',
    name: 'Barbell Calf Raises',
    aliases: ['Barbell Calf Raise', 'Standing Calf Raise'],
    pattern: 'isolation',
    primaryMuscles: ['calves'],
    secondaryMuscles: [],
    equipment: ['barbell'],
    unit: 'kg',
    increment: 5,
    repRange: [10, 15],
    cue: 'Full stretch at the bottom, full contraction at the top. Slow, not bouncy.',
    usesBodyweight: false,
    bodyweightFactor: 1,
    role: 'prescribed',
  },

  /* ---------------- Saturday: cardio and abs ---------------- */
  {
    id: 'hanging-leg-raises',
    name: 'Hanging Leg Raises',
    aliases: ['Hanging Leg Raise', 'Hanging Knee Raise'],
    pattern: 'core',
    primaryMuscles: ['abs'],
    secondaryMuscles: ['obliques', 'grip'],
    equipment: ['pullup_bar', 'bodyweight'],
    unit: 'reps',
    increment: 0,
    repRange: [8, 15],
    progressionLadder: ['leg-raises', 'hanging-leg-raises'],
    cue: 'Stop the swing before each rep. Curl the pelvis rather than just lifting the legs.',
    usesBodyweight: true,
    // Reasoned from segment mass, not measured — legs, with the trunk stabilising. See docs/TODO.md's Exercise substitution entry (commit 5ce8d44).
    bodyweightFactor: 0.35,
    role: 'prescribed',
  },
  {
    id: 'treadmill-intervals',
    name: 'Treadmill Intervals',
    aliases: ['Treadmill', 'Walk Run Intervals', 'Cardio'],
    pattern: 'cardio',
    primaryMuscles: ['cardio'],
    secondaryMuscles: [],
    equipment: ['treadmill'],
    unit: 'time',
    increment: 0,
    repRange: [1, 1],
    cue: 'Five minutes walking, five minutes running, repeated. Walk in zone 2, run in zone 4.',
    usesBodyweight: false,
    bodyweightFactor: 1,
    role: 'prescribed',
  },

  /* ---------------- Available for the Daily Quest and Instant Dungeons ---------------- */
  {
    id: 'pushups',
    name: 'Pushups',
    aliases: ['Push-ups', 'Push Ups'],
    pattern: 'horizontal_push',
    primaryMuscles: ['chest'],
    secondaryMuscles: ['triceps', 'front_delts'],
    equipment: ['bodyweight'],
    unit: 'reps',
    increment: 0,
    repRange: [10, 30],
    progressionLadder: ['incline-pushups', 'pushups', 'diamond-pushups'],
    cue: 'Body in one line from head to heels.',
    usesBodyweight: true,
    // The most commonly cited figure for a standard pushup (~64% of bodyweight),
    // but not independently verified against a primary source here — see
    // docs/TODO.md's Exercise substitution entry (commit 5ce8d44).
    bodyweightFactor: 0.64,
    role: 'prescribed',
  },
  {
    id: 'bodyweight-squat',
    name: 'Bodyweight Squats',
    aliases: ['Air Squat', 'Bodyweight Squat'],
    pattern: 'squat',
    primaryMuscles: ['quads'],
    secondaryMuscles: ['glutes'],
    equipment: ['bodyweight'],
    unit: 'reps',
    increment: 0,
    repRange: [15, 40],
    cue: 'Sit down between the heels. Full depth every rep.',
    usesBodyweight: true,
    // Reasoned, not measured — trunk plus most of the legs. See docs/TODO.md's Exercise substitution entry (commit 5ce8d44).
    bodyweightFactor: 0.65,
    role: 'prescribed',
  },
  {
    id: 'situps',
    name: 'Sit-ups',
    aliases: ['Situps', 'Sit Ups'],
    pattern: 'core',
    primaryMuscles: ['abs'],
    secondaryMuscles: ['obliques'],
    equipment: ['bodyweight'],
    unit: 'reps',
    increment: 0,
    repRange: [15, 40],
    cue: 'Do not yank on the neck. Lead with the ribs.',
    usesBodyweight: true,
    // Reasoned, not measured — the trunk, not the whole body. See docs/TODO.md's Exercise substitution entry (commit 5ce8d44).
    bodyweightFactor: 0.45,
    role: 'prescribed',
  },

  /* ---------------- Fallback library ----------------
   * Never prescribed, never a routine default, never promoted by mastering
   * one. Exists only so `substitutesFor` (commit 5) has an answer for the
   * groups the equipment-desert audit found (commit 5d33216). Two entries
   * from that table are deliberately absent: Skipping (needs a jump rope,
   * which is not in EquipmentSchema) and Plate Raise (needs a loose plate,
   * same gap) — both would have to be tagged with equipment they do not
   * really require, which is worse than seeding one fewer exercise.
   */
  {
    id: 'inverted-row',
    name: 'Inverted Row',
    aliases: ['Body Row', 'Table Row', 'Bar Row'],
    pattern: 'horizontal_pull',
    primaryMuscles: ['upper_back'],
    secondaryMuscles: ['lats', 'biceps', 'rear_delts'],
    // The audit's minimum implement is "a bar, rings, or a table edge" — a squat
    // rack or Smith machine bar is the closest match the equipment
    // vocabulary has, so this tag is approximate rather than exact.
    equipment: ['pullup_bar', 'bodyweight'],
    unit: 'reps',
    increment: 0,
    repRange: [8, 15],
    cue: 'Bar at hip height. Body straight, pull the chest to the bar.',
    usesBodyweight: true,
    // Reasoned, not measured — a lower bar and shallower body angle move
    // less than a dead hang. Same reasoned-not-measured method as commit
    // 5ce8d44, extended to fallbacks here.
    bodyweightFactor: 0.55,
    role: 'fallback',
  },
  {
    id: 'chin-ups',
    name: 'Chin-ups',
    aliases: ['Chinups', 'Underhand Pull-ups'],
    // Modelled with biceps as the primary mover (not lats, as Pull-ups is)
    // so it can actually fill the isolation/biceps gap the audit found — an identical
    // exercise to Pull-ups here would not help when the curl station, not
    // the bar, is what is occupied.
    pattern: 'vertical_pull',
    primaryMuscles: ['biceps'],
    secondaryMuscles: ['lats', 'upper_back'],
    equipment: ['pullup_bar'],
    unit: 'reps',
    increment: 0,
    repRange: [4, 12],
    cue: 'Underhand, shoulder width. Chin clears the bar.',
    usesBodyweight: true,
    // Reasoned, not measured — close to a dead hang, same as Pull-ups. See docs/TODO.md's Exercise substitution entry (commit 5ce8d44).
    bodyweightFactor: 0.9,
    role: 'fallback',
  },
  {
    id: 'single-arm-dumbbell-row',
    name: 'Single-arm Dumbbell Row (No Bench)',
    aliases: ['Bent-over One Arm Row', 'Suitcase Row'],
    pattern: 'horizontal_pull',
    primaryMuscles: ['upper_back'],
    secondaryMuscles: ['lats', 'biceps', 'rear_delts'],
    equipment: ['dumbbell'],
    unit: 'kg',
    increment: 2,
    repRange: [8, 15],
    cue: 'Hinge at the hip, flat back. Row to the hip, not the shoulder.',
    usesBodyweight: false,
    bodyweightFactor: 1,
    role: 'fallback',
  },
  {
    id: 'dumbbell-lateral-raise',
    name: 'Dumbbell Lateral Raise',
    aliases: ['DB Lateral Raise', 'Side Raise'],
    pattern: 'isolation',
    primaryMuscles: ['side_delts'],
    secondaryMuscles: [],
    equipment: ['dumbbell'],
    unit: 'kg',
    increment: 1,
    repRange: [10, 20],
    cue: 'Lead with the elbows. Stop at shoulder height.',
    usesBodyweight: false,
    bodyweightFactor: 1,
    role: 'fallback',
  },
  {
    id: 'prone-ytw-raise',
    name: 'Prone Y-T-W Raise',
    aliases: ['YTW Raise', 'Prone Raise'],
    pattern: 'isolation',
    primaryMuscles: ['rear_delts'],
    secondaryMuscles: ['upper_back'],
    equipment: ['bodyweight'],
    unit: 'reps',
    increment: 0,
    repRange: [10, 20],
    cue: 'Face down on a bench or the floor. Thumbs up, squeeze the shoulder blades, not the lower back.',
    usesBodyweight: true,
    // Reasoned, not measured — only the arms move against gravity. See docs/TODO.md's Exercise substitution entry (commit 5ce8d44).
    bodyweightFactor: 0.15,
    role: 'fallback',
  },
  {
    id: 'dumbbell-shrug',
    name: 'Dumbbell Shrug',
    aliases: ['DB Shrug'],
    pattern: 'isolation',
    primaryMuscles: ['traps'],
    secondaryMuscles: ['grip'],
    equipment: ['dumbbell'],
    unit: 'kg',
    increment: 2,
    repRange: [10, 20],
    cue: 'Straight up and down. No rolling the shoulders.',
    usesBodyweight: false,
    bodyweightFactor: 1,
    role: 'fallback',
  },
  {
    id: 'barbell-shrug',
    name: 'Barbell Shrug',
    aliases: [],
    pattern: 'isolation',
    primaryMuscles: ['traps'],
    secondaryMuscles: ['grip'],
    equipment: ['barbell'],
    unit: 'kg',
    increment: 5,
    repRange: [8, 15],
    cue: 'Straight up and down. No rolling the shoulders.',
    usesBodyweight: false,
    bodyweightFactor: 1,
    role: 'fallback',
  },
  {
    id: 'towel-curl',
    name: 'Towel Curl',
    aliases: ['Isometric Towel Curl'],
    pattern: 'isolation',
    primaryMuscles: ['biceps'],
    secondaryMuscles: ['forearms'],
    equipment: ['bodyweight'],
    unit: 'time',
    increment: 0,
    repRange: [1, 1],
    cue: 'Loop a towel under one foot. Curl against it as hard as you can hold.',
    // Isometric and self-resisted — no bodyweight mass is actually moved, so
    // this earns hard-set and work-interval credit but no tonnage.
    usesBodyweight: false,
    bodyweightFactor: 1,
    role: 'fallback',
  },
  {
    id: 'single-leg-glute-bridge',
    name: 'Single-leg Glute Bridge',
    aliases: ['Single Leg Hip Bridge'],
    pattern: 'hinge',
    primaryMuscles: ['hamstrings'],
    secondaryMuscles: ['glutes'],
    equipment: ['bodyweight'],
    unit: 'reps',
    increment: 0,
    repRange: [10, 20],
    cue: 'One foot down, hips square. Squeeze at the top, control the lower.',
    usesBodyweight: true,
    // Reasoned, not measured — one leg carries the hips, not the whole body. See docs/TODO.md's Exercise substitution entry (commit 5ce8d44).
    bodyweightFactor: 0.35,
    role: 'fallback',
  },
  {
    id: 'nordic-curl',
    name: 'Nordic Curl',
    aliases: ['Nordic Hamstring Curl'],
    pattern: 'isolation',
    primaryMuscles: ['hamstrings'],
    secondaryMuscles: ['glutes'],
    equipment: ['bodyweight'],
    unit: 'reps',
    increment: 0,
    repRange: [3, 10],
    cue: 'Kneeling, ankles anchored. Lower under control for as long as possible and catch yourself at the bottom.',
    usesBodyweight: true,
    // Reasoned, not measured — the torso and hips lower under the hamstrings' control. See docs/TODO.md's Exercise substitution entry (commit 5ce8d44).
    bodyweightFactor: 0.8,
    role: 'fallback',
  },
  {
    id: 'split-squat',
    name: 'Split Squat',
    aliases: ['Bulgarian Split Squat', 'Rear-foot Elevated Split Squat'],
    pattern: 'lunge',
    primaryMuscles: ['quads'],
    secondaryMuscles: ['glutes'],
    equipment: ['bodyweight'],
    unit: 'reps',
    increment: 0,
    repRange: [10, 20],
    cue: 'Rear foot elevated if you have something to put it on. Front shin stays vertical.',
    usesBodyweight: true,
    // Reasoned, not measured — one leg carries nearly the whole body through the rep. See docs/TODO.md's Exercise substitution entry (commit 5ce8d44).
    bodyweightFactor: 0.85,
    role: 'fallback',
  },
  {
    id: 'wall-sit',
    name: 'Wall Sit',
    aliases: [],
    pattern: 'squat',
    primaryMuscles: ['quads'],
    secondaryMuscles: ['glutes'],
    equipment: ['bodyweight'],
    unit: 'time',
    increment: 0,
    repRange: [1, 1],
    cue: 'Thighs parallel to the floor, back flat against the wall.',
    // unit: 'time' sets always log reps: 0, and tonnage() multiplies by reps,
    // so bodyweightFactor could never contribute here regardless of value —
    // left false rather than seed a number that can never be read.
    usesBodyweight: false,
    bodyweightFactor: 1,
    role: 'fallback',
  },
  {
    id: 'standing-calf-raise',
    name: 'Standing Calf Raise',
    aliases: ['Bodyweight Calf Raise'],
    pattern: 'isolation',
    primaryMuscles: ['calves'],
    secondaryMuscles: [],
    equipment: ['bodyweight'],
    unit: 'reps',
    increment: 0,
    repRange: [15, 30],
    cue: 'Full stretch at the bottom, pause at the top.',
    usesBodyweight: true,
    // Genuinely unsourced — how much a two-footed raise is worth versus a
    // loaded barbell calf raise is not something this estimate is confident
    // about. Flagged rather than presented as measured. See docs/TODO.md's Exercise substitution entry (commit 5ce8d44).
    bodyweightFactor: 0.9,
    role: 'fallback',
  },
  {
    id: 'stair-climb',
    name: 'Stair Climb',
    aliases: ['Stairs', 'Stair Sprints'],
    pattern: 'cardio',
    primaryMuscles: ['cardio'],
    secondaryMuscles: ['quads', 'glutes'],
    equipment: ['bodyweight'],
    unit: 'time',
    increment: 0,
    repRange: [1, 1],
    cue: 'Steady pace up, walk down to recover. Repeat for the interval.',
    usesBodyweight: false,
    bodyweightFactor: 1,
    role: 'fallback',
  },
  {
    id: 'outdoor-run',
    name: 'Outdoor Run',
    aliases: ['Run', 'Jog'],
    pattern: 'cardio',
    primaryMuscles: ['cardio'],
    secondaryMuscles: [],
    equipment: ['bodyweight'],
    unit: 'time',
    increment: 0,
    repRange: [1, 1],
    cue: 'Same walk-run structure as the treadmill: five easy, five hard, repeated.',
    usesBodyweight: false,
    bodyweightFactor: 1,
    role: 'fallback',
  },
  {
    id: 'burpees',
    name: 'Burpees',
    aliases: [],
    pattern: 'cardio',
    primaryMuscles: ['cardio'],
    secondaryMuscles: ['chest', 'quads'],
    equipment: ['bodyweight'],
    unit: 'reps',
    increment: 0,
    repRange: [10, 30],
    cue: 'Chest to the floor, full jump at the top. Keep the pace honest.',
    usesBodyweight: true,
    // Reasoned, not measured — full body through the rep, close to a pushup-plus-jump. See docs/TODO.md's Exercise substitution entry (commit 5ce8d44).
    bodyweightFactor: 0.7,
    role: 'fallback',
  },

  /* ---------------- Fallback library, round 2: equipment-substitution audit ----------------
   * Extends the commit 5d33216 audit past groups it didn't reach: no loaded hinge movement
   * existed anywhere in the library (no Romanian deadlift), no exercise named glutes as a
   * primary mover at all, horizontal_pull/upper_back had no cable or machine answer, chest
   * and front_delts pressing had no free-weight fallback once both barbell and cable were
   * occupied, biceps had no dumbbell curl, the carry pattern was unused, and `bands` —
   * offered as equipment since the Awakening Test's picker (M2) — had never been asked for
   * by a single exercise. Found by re-running the same coverage method as commit 5d33216
   * against the full muscle and pattern lists, not the equipment-desert test alone.
   */
  {
    id: 'dumbbell-bench-press',
    name: 'Dumbbell Bench Press',
    aliases: ['DB Bench Press', 'Dumbbell Chest Press'],
    pattern: 'horizontal_push',
    primaryMuscles: ['chest'],
    secondaryMuscles: ['front_delts', 'triceps'],
    equipment: ['dumbbell', 'bench'],
    unit: 'kg',
    increment: 2,
    repRange: [8, 12],
    cue: 'Press up and slightly in, over the chest rather than the shoulders.',
    usesBodyweight: false,
    bodyweightFactor: 1,
    role: 'fallback',
  },
  {
    id: 'dumbbell-shoulder-press',
    name: 'Dumbbell Shoulder Press',
    aliases: ['DB Shoulder Press', 'Seated Dumbbell Press'],
    pattern: 'vertical_push',
    primaryMuscles: ['front_delts'],
    secondaryMuscles: ['side_delts', 'triceps'],
    equipment: ['dumbbell'],
    unit: 'kg',
    increment: 2,
    repRange: [8, 12],
    cue: 'Press up and slightly in until the dumbbells nearly touch overhead.',
    usesBodyweight: false,
    bodyweightFactor: 1,
    role: 'fallback',
  },
  {
    id: 'bench-dips',
    name: 'Bench Dips',
    aliases: ['Tricep Bench Dips', 'Chair Dips'],
    pattern: 'isolation',
    primaryMuscles: ['triceps'],
    secondaryMuscles: ['front_delts', 'chest'],
    equipment: ['bodyweight', 'bench'],
    unit: 'reps',
    increment: 0,
    repRange: [10, 20],
    cue: 'Elbows point straight back, not out. Lower until the upper arm is level with the bench.',
    usesBodyweight: true,
    // Reasoned, not measured — feet on the floor share some of the load with the arms, less than a straight-bar dip would. See docs/TODO.md's Exercise substitution entry (commit 5ce8d44).
    bodyweightFactor: 0.65,
    role: 'fallback',
  },
  {
    id: 'dumbbell-bicep-curl',
    name: 'Dumbbell Bicep Curl',
    aliases: ['DB Curl', 'Alternating Dumbbell Curl'],
    pattern: 'isolation',
    primaryMuscles: ['biceps'],
    secondaryMuscles: ['forearms'],
    equipment: ['dumbbell'],
    unit: 'kg',
    increment: 1,
    repRange: [8, 12],
    cue: 'Elbows pinned to the sides. No swing — if the hips move, the weight is too heavy.',
    usesBodyweight: false,
    bodyweightFactor: 1,
    role: 'fallback',
  },
  {
    id: 'seated-cable-row',
    name: 'Seated Cable Row',
    aliases: ['Cable Row', 'Low Pulley Row'],
    pattern: 'horizontal_pull',
    primaryMuscles: ['upper_back'],
    secondaryMuscles: ['lats', 'biceps'],
    equipment: ['cable'],
    unit: 'kg',
    increment: PIN_STEP,
    repRange: [8, 12],
    cue: 'Chest up, pull to the sternum. Let the shoulder blades protract fully at the stretch.',
    usesBodyweight: false,
    bodyweightFactor: 1,
    role: 'fallback',
  },
  {
    id: 'face-pull',
    name: 'Face Pull',
    aliases: ['Cable Face Pull', 'Rope Face Pull'],
    pattern: 'isolation',
    primaryMuscles: ['rear_delts'],
    secondaryMuscles: ['rotator_cuff', 'upper_back', 'traps'],
    equipment: ['cable'],
    unit: 'kg',
    increment: PIN_STEP,
    repRange: [12, 20],
    cue: 'Pull to the forehead, hands finishing beside the ears, thumbs pointing back.',
    usesBodyweight: false,
    bodyweightFactor: 1,
    role: 'fallback',
  },
  {
    id: 'dumbbell-reverse-fly',
    name: 'Dumbbell Reverse Fly',
    aliases: ['Bent-over Reverse Fly', 'Rear Delt Fly'],
    pattern: 'isolation',
    primaryMuscles: ['rear_delts'],
    secondaryMuscles: ['upper_back'],
    equipment: ['dumbbell'],
    unit: 'kg',
    increment: 1,
    repRange: [12, 20],
    cue: 'Hinge at the hips to near-horizontal. Raise with straight-ish arms, lead with the elbows.',
    usesBodyweight: false,
    bodyweightFactor: 1,
    role: 'fallback',
  },
  {
    id: 'dumbbell-goblet-squat',
    name: 'Dumbbell Goblet Squat',
    aliases: ['Goblet Squat'],
    pattern: 'squat',
    primaryMuscles: ['quads'],
    secondaryMuscles: ['glutes'],
    equipment: ['dumbbell'],
    unit: 'kg',
    increment: 2,
    repRange: [10, 15],
    cue: 'Hold the dumbbell vertically against the chest. Elbows split the knees at the bottom.',
    usesBodyweight: false,
    bodyweightFactor: 1,
    role: 'fallback',
  },
  {
    id: 'barbell-romanian-deadlift',
    name: 'Barbell Romanian Deadlift',
    aliases: ['Romanian Deadlift', 'RDL', 'Barbell RDL'],
    pattern: 'hinge',
    primaryMuscles: ['hamstrings'],
    secondaryMuscles: ['glutes', 'lower_back'],
    equipment: ['barbell'],
    unit: 'kg',
    increment: 5,
    repRange: [6, 10],
    cue: 'Push the hips back, bar stays against the thighs. Stop when the hamstrings stop letting the back stay flat.',
    usesBodyweight: false,
    bodyweightFactor: 1,
    role: 'fallback',
  },
  {
    id: 'dumbbell-romanian-deadlift',
    name: 'Dumbbell Romanian Deadlift',
    aliases: ['Dumbbell RDL', 'DB RDL'],
    pattern: 'hinge',
    primaryMuscles: ['hamstrings'],
    secondaryMuscles: ['glutes', 'lower_back'],
    equipment: ['dumbbell'],
    unit: 'kg',
    increment: 2,
    repRange: [8, 12],
    cue: 'Dumbbells ride down the front of the legs. Push the hips back rather than squatting down.',
    usesBodyweight: false,
    bodyweightFactor: 1,
    role: 'fallback',
  },
  {
    id: 'barbell-hip-thrust',
    name: 'Barbell Hip Thrust',
    aliases: ['Hip Thrust', 'Glute Bridge Barbell'],
    pattern: 'hinge',
    primaryMuscles: ['glutes'],
    secondaryMuscles: ['hamstrings'],
    equipment: ['barbell', 'bench'],
    unit: 'kg',
    increment: 5,
    repRange: [8, 15],
    cue: 'Upper back on the bench, chin tucked. Drive through the heels to full hip extension, pause at the top.',
    usesBodyweight: false,
    bodyweightFactor: 1,
    role: 'fallback',
  },
  {
    id: 'seated-calf-raise-machine',
    name: 'Seated Calf Raise (Machine)',
    aliases: ['Seated Calf Raise', 'Machine Seated Calf Raise'],
    pattern: 'isolation',
    primaryMuscles: ['calves'],
    secondaryMuscles: [],
    equipment: ['machine'],
    unit: 'kg',
    increment: PIN_STEP,
    // The bent knee de-tensions the gastrocnemius and shifts the load onto the
    // soleus, which is why this is kept as its own exercise rather than an
    // alias of the standing raise — it trains a different part of the same
    // muscle group, not the same movement on a different implement.
    repRange: [12, 20],
    cue: 'Knees bent under the pad. Full stretch at the bottom, pause at the top.',
    usesBodyweight: false,
    bodyweightFactor: 1,
    role: 'fallback',
  },
  {
    id: 'farmers-carry',
    name: "Farmer's Carry",
    aliases: ['Farmers Walk', 'Suitcase Carry'],
    pattern: 'carry',
    primaryMuscles: ['grip', 'forearms'],
    secondaryMuscles: ['traps', 'abs'],
    equipment: ['dumbbell'],
    unit: 'time',
    increment: 0,
    repRange: [1, 1],
    cue: 'Heaviest dumbbells you can hold for the interval without the grip failing first. Walk tall, shoulders back.',
    // Externally loaded, not bodyweight — same reasoning as Stair Climb: a
    // time unit always logs reps: 0, so this can never contribute tonnage
    // regardless of the value here.
    usesBodyweight: false,
    bodyweightFactor: 1,
    role: 'fallback',
  },
  {
    id: 'band-external-rotation',
    name: 'Band External Rotation',
    aliases: ['Cuff External Rotation', 'Band Shoulder External Rotation'],
    pattern: 'isolation',
    primaryMuscles: ['rotator_cuff'],
    secondaryMuscles: ['rear_delts'],
    equipment: ['bands'],
    unit: 'reps',
    increment: 0,
    repRange: [12, 20],
    cue: 'Elbow pinned to the ribs at 90 degrees. Rotate the forearm out, nothing else moves.',
    usesBodyweight: false,
    bodyweightFactor: 1,
    role: 'fallback',
  },
  {
    id: 'band-pull-apart',
    name: 'Band Pull-Apart',
    aliases: ['Resistance Band Pull Apart'],
    pattern: 'isolation',
    primaryMuscles: ['rear_delts'],
    secondaryMuscles: ['upper_back', 'traps'],
    equipment: ['bands'],
    unit: 'reps',
    increment: 0,
    repRange: [15, 25],
    cue: 'Arms straight at shoulder height. Pull the band apart until it touches the chest, squeeze the blades.',
    usesBodyweight: false,
    bodyweightFactor: 1,
    role: 'fallback',
  },
]

/**
 * The six training days. Day numbers match `Date.prototype.getDay`, so Sunday
 * is 0 and is deliberately absent — Sunday is rest.
 *
 * Gate ranks here are starting values. Once there is history the real rank is
 * computed from planned tonnage and intensity by `gateDifficulty`.
 */
export const SEED_ROUTINES: readonly Routine[] = [
  {
    id: 'monday-cst',
    dayOfWeek: 1,
    name: 'CST Gate',
    gateRank: 'C',
    blocks: [
      { type: 'single', items: [{ exerciseId: 'incline-barbell-press', sets: 4, repRange: [5, 8], restSec: 180 }] },
      { type: 'single', items: [{ exerciseId: 'machine-shoulder-press', sets: 3, repRange: [8, 12], restSec: 120 }] },
      { type: 'single', items: [{ exerciseId: 'skullcrusher', sets: 3, repRange: [8, 12], restSec: 90 }] },
      { type: 'single', items: [{ exerciseId: 'cable-fly', sets: 3, repRange: [10, 15], restSec: 75 }] },
      { type: 'single', items: [{ exerciseId: 'machine-lateral-raise', sets: 3, repRange: [12, 20], restSec: 60 }] },
      { type: 'single', items: [{ exerciseId: 'front-raises', sets: 2, repRange: [12, 15], restSec: 60 }] },
      { type: 'single', items: [{ exerciseId: 'diamond-pushups', sets: 3, repRange: [8, 20], restSec: 90 }] },
    ],
  },
  {
    id: 'tuesday-back-biceps',
    dayOfWeek: 2,
    name: 'Back and Biceps Gate',
    gateRank: 'C',
    blocks: [
      { type: 'single', items: [{ exerciseId: 'one-arm-cable-lat-pulldown', sets: 3, repRange: [8, 12], restSec: 90 }] },
      { type: 'single', items: [{ exerciseId: 'pull-ups', sets: 4, repRange: [5, 12], restSec: 150 }] },
      { type: 'single', items: [{ exerciseId: 'dumbbell-row', sets: 3, repRange: [8, 12], restSec: 120 }] },
      { type: 'single', items: [{ exerciseId: 'cable-shrug', sets: 3, repRange: [10, 15], restSec: 75 }] },
      { type: 'single', items: [{ exerciseId: 'machine-reverse-fly', sets: 3, repRange: [12, 20], restSec: 60 }] },
      { type: 'single', items: [{ exerciseId: 'cable-bicep-curl', sets: 3, repRange: [10, 15], restSec: 60 }] },
    ],
  },
  {
    id: 'wednesday-abs-biceps',
    dayOfWeek: 3,
    name: 'Abs and Biceps Gate',
    gateRank: 'D',
    blocks: [
      { type: 'single', items: [{ exerciseId: 'machine-preacher-curl', sets: 3, repRange: [10, 15], restSec: 75 }] },
      { type: 'single', items: [{ exerciseId: 'cable-bicep-curl', sets: 3, repRange: [10, 15], restSec: 60 }] },
      { type: 'single', items: [{ exerciseId: 'strict-curl', sets: 3, repRange: [6, 10], restSec: 90 }] },
      { type: 'single', items: [{ exerciseId: 'leg-raises', sets: 3, repRange: [12, 20], restSec: 60 }] },
      { type: 'single', items: [{ exerciseId: 'machine-abs-crunch', sets: 3, repRange: [10, 15], restSec: 60 }] },
      { type: 'single', items: [{ exerciseId: 'cable-crunch', sets: 3, repRange: [10, 15], restSec: 60 }] },
    ],
  },
  {
    id: 'thursday-cst-supersets',
    dayOfWeek: 4,
    name: 'CST Gate (Supersets)',
    gateRank: 'C',
    // The `+` pairs in the brief are real supersets, performed alternating.
    blocks: [
      {
        type: 'superset',
        items: [
          { exerciseId: 'incline-pushups', sets: 3, repRange: [10, 20], restSec: 0 },
          { exerciseId: 'cable-chest-press-mid', sets: 3, repRange: [10, 15], restSec: 90 },
        ],
      },
      {
        type: 'superset',
        items: [
          { exerciseId: 'pike-pushups', sets: 3, repRange: [8, 15], restSec: 0 },
          { exerciseId: 'cable-chest-press-low', sets: 3, repRange: [10, 15], restSec: 90 },
        ],
      },
      {
        type: 'superset',
        items: [
          { exerciseId: 'diamond-pushups', sets: 3, repRange: [8, 20], restSec: 0 },
          { exerciseId: 'cable-chest-press-high', sets: 3, repRange: [10, 15], restSec: 90 },
        ],
      },
      { type: 'single', items: [{ exerciseId: 'machine-shoulder-press', sets: 3, repRange: [8, 12], restSec: 120 }] },
      { type: 'single', items: [{ exerciseId: 'tricep-overhead-extension', sets: 3, repRange: [10, 15], restSec: 75 }] },
    ],
  },
  {
    id: 'friday-legs',
    dayOfWeek: 5,
    name: 'Legs Gate',
    gateRank: 'B',
    blocks: [
      { type: 'single', items: [{ exerciseId: 'barbell-squat', sets: 4, repRange: [5, 8], restSec: 210 }] },
      { type: 'single', items: [{ exerciseId: 'leg-press', sets: 3, repRange: [10, 15], restSec: 150 }] },
      {
        type: 'superset',
        items: [
          { exerciseId: 'hamstring-curl', sets: 3, repRange: [10, 15], restSec: 0 },
          { exerciseId: 'leg-extension', sets: 3, repRange: [12, 15], restSec: 90 },
        ],
      },
      { type: 'single', items: [{ exerciseId: 'barbell-calf-raise', sets: 4, repRange: [10, 15], restSec: 75 }] },
    ],
  },
  {
    id: 'saturday-cardio-abs',
    dayOfWeek: 6,
    name: 'Cardio and Abs Gate',
    gateRank: 'D',
    blocks: [
      { type: 'single', items: [{ exerciseId: 'leg-raises', sets: 3, repRange: [12, 20], restSec: 60 }] },
      { type: 'single', items: [{ exerciseId: 'cable-crunch', sets: 3, repRange: [10, 15], restSec: 60 }] },
      { type: 'single', items: [{ exerciseId: 'hanging-leg-raises', sets: 3, repRange: [8, 15], restSec: 75 }] },
      { type: 'single', items: [{ exerciseId: 'treadmill-intervals', sets: 1, repRange: [1, 1], restSec: 0 }] },
    ],
  },
]

/** Lookup by id, for the many callers that resolve an exercise from a set log. */
export const SEED_EXERCISE_BY_ID: ReadonlyMap<string, Exercise> = new Map(
  SEED_EXERCISES.map((exercise) => [exercise.id, exercise]),
)

export function seedExercise(id: string): Exercise | undefined {
  return SEED_EXERCISE_BY_ID.get(id)
}

export function routineForDayOfWeek(dayOfWeek: number): Routine | undefined {
  return SEED_ROUTINES.find((routine) => routine.dayOfWeek === dayOfWeek)
}
