/**
 * The seed exercise library and routines, encoding the hunter's actual training
 * week rather than a published programme.
 *
 * Original spellings from the brief are kept as `aliases` so search finds each
 * exercise by the name it is actually called. The engine applies progressive
 * overload to these movements; it does not replace them with something else.
 *
 * Increments follow the brief: upper-body isolation 1.25 to 2.5 kg, upper
 * compound 2.5 kg, lower compound 5 kg, and cables and machines one pin step.
 */
import type { Exercise, Routine } from '../domain/types'

/** One pin step on the cable stacks and most selectorised machines. */
const PIN_STEP = 2.5

export const SEED_EXERCISES: readonly Exercise[] = [
  /* ---------------- Monday: chest, shoulders, triceps ---------------- */
  {
    id: 'incline-barbell-press',
    name: 'Incline Barbell Press',
    aliases: ['Incline Barbel Press', 'Incline Bench Press', 'Incline Press'],
    pattern: 'horizontal_push',
    primaryMuscles: ['chest'],
    secondaryMuscles: ['front_delts', 'triceps'],
    equipment: ['barbell', 'bench'],
    unit: 'kg',
    increment: 2.5,
    repRange: [5, 8],
    standardLift: 'incline_bench',
    cue: 'Elbows about 45 degrees from the torso. Bar to the upper chest, not the throat.',
    usesBodyweight: false,
    bodyweightFactor: 1,
  },
  {
    id: 'machine-shoulder-press',
    name: 'Machine Shoulder Press',
    aliases: ['Shoulder Press Machine'],
    pattern: 'vertical_push',
    primaryMuscles: ['front_delts'],
    secondaryMuscles: ['side_delts', 'triceps'],
    equipment: ['machine'],
    unit: 'kg',
    increment: PIN_STEP,
    repRange: [8, 12],
    cue: 'Do not lock out hard at the top. Keep the ribs down.',
    usesBodyweight: false,
    bodyweightFactor: 1,
  },
  {
    id: 'skullcrusher',
    name: 'Skullcrusher',
    aliases: ['Skull Crusher', 'Lying Triceps Extension'],
    pattern: 'isolation',
    primaryMuscles: ['triceps'],
    secondaryMuscles: [],
    equipment: ['ez_bar', 'bench'],
    unit: 'kg',
    increment: 1.25,
    repRange: [8, 12],
    cue: 'Elbows stay pointed at the ceiling. Only the forearm moves.',
    usesBodyweight: false,
    bodyweightFactor: 1,
  },
  {
    id: 'cable-fly',
    name: 'Cable Fly',
    aliases: ['Cable Flye', 'Cable Crossover'],
    pattern: 'isolation',
    primaryMuscles: ['chest'],
    secondaryMuscles: ['front_delts'],
    equipment: ['cable'],
    unit: 'kg',
    increment: PIN_STEP,
    repRange: [10, 15],
    cue: 'Slight elbow bend held constant. Squeeze at the midline, do not clap.',
    usesBodyweight: false,
    bodyweightFactor: 1,
  },
  {
    id: 'machine-lateral-raise',
    name: 'Machine Lateral Raise',
    aliases: ['Lateral Raise Machine', 'Machine Side Raise'],
    pattern: 'isolation',
    primaryMuscles: ['side_delts'],
    secondaryMuscles: [],
    equipment: ['machine'],
    unit: 'kg',
    increment: PIN_STEP,
    repRange: [12, 20],
    cue: 'Lead with the elbow. Stop at shoulder height.',
    usesBodyweight: false,
    bodyweightFactor: 1,
  },
  {
    id: 'front-raises',
    name: 'Front Raises',
    aliases: ['Front Raise'],
    pattern: 'isolation',
    primaryMuscles: ['front_delts'],
    secondaryMuscles: [],
    equipment: ['dumbbell'],
    unit: 'kg',
    increment: 1.25,
    repRange: [12, 15],
    cue: 'The pressing already trains this head hard. Keep the load honest and the swing out of it.',
    usesBodyweight: false,
    bodyweightFactor: 1,
  },
  {
    id: 'diamond-pushups',
    name: 'Diamond Pushups',
    aliases: ['Dimond Pushups', 'Diamond Push-ups', 'Close-grip Pushups'],
    pattern: 'horizontal_push',
    primaryMuscles: ['triceps'],
    secondaryMuscles: ['chest', 'front_delts'],
    equipment: ['bodyweight'],
    unit: 'reps',
    increment: 0,
    repRange: [8, 20],
    progressionLadder: ['incline-pushups', 'pike-pushups', 'diamond-pushups'],
    cue: 'Hands together under the sternum. Elbows brush the ribs.',
    usesBodyweight: true,
    // Reasoned from segment mass, not measured — see docs/substitution-plan.md §7.
    bodyweightFactor: 0.66,
  },

  /* ---------------- Tuesday: back and biceps ---------------- */
  {
    id: 'one-arm-cable-lat-pulldown',
    name: '1-Arm Cable Lat Pulldown',
    aliases: ['1-Arm Cabel Lat Pulldown', 'Single Arm Lat Pulldown', 'One Arm Pulldown'],
    pattern: 'vertical_pull',
    primaryMuscles: ['lats'],
    secondaryMuscles: ['biceps', 'upper_back'],
    equipment: ['cable'],
    unit: 'kg',
    increment: PIN_STEP,
    repRange: [8, 12],
    cue: 'Let the shoulder rise at the top, then drive the elbow down and back.',
    usesBodyweight: false,
    bodyweightFactor: 1,
  },
  {
    id: 'pull-ups',
    name: 'Pull-ups',
    aliases: ['Pullups', 'Pull Ups', 'Chin-ups'],
    pattern: 'vertical_pull',
    primaryMuscles: ['lats'],
    secondaryMuscles: ['biceps', 'upper_back', 'grip'],
    equipment: ['pullup_bar', 'bodyweight'],
    unit: 'reps',
    increment: 0,
    repRange: [5, 12],
    standardLift: 'pullup',
    cue: 'Full hang at the bottom. Chest to the bar, no kipping.',
    usesBodyweight: true,
    // Reasoned, not measured — a dead hang moves nearly all of it. See §7.
    bodyweightFactor: 0.95,
  },
  {
    id: 'dumbbell-row',
    name: 'Dumbbell Row',
    aliases: ['Dumble Row', 'One Arm Row', 'DB Row'],
    pattern: 'horizontal_pull',
    primaryMuscles: ['upper_back'],
    secondaryMuscles: ['lats', 'biceps', 'grip'],
    equipment: ['dumbbell', 'bench'],
    unit: 'kg',
    increment: 2.5,
    repRange: [8, 12],
    cue: 'Pull to the hip, not the armpit. Keep the torso still.',
    usesBodyweight: false,
    bodyweightFactor: 1,
  },
  {
    id: 'cable-shrug',
    name: 'Cable Shrug',
    // The hunter calls this a "Cable Shrug-in": standing at a low pulley holding
    // a straight bar at hip height and shrugging.
    aliases: ['Cable Shrug-in', 'Cable Shrug In', 'Low Pulley Shrug'],
    pattern: 'isolation',
    primaryMuscles: ['traps'],
    secondaryMuscles: ['grip', 'upper_back'],
    equipment: ['cable'],
    unit: 'kg',
    increment: PIN_STEP,
    repRange: [10, 15],
    cue: 'Straight up and down. No rolling — rolling the shoulders adds nothing and grinds the joint.',
    usesBodyweight: false,
    bodyweightFactor: 1,
  },
  {
    id: 'machine-reverse-fly',
    name: 'Machine Reverse Fly',
    aliases: ['Reverse Fly Machine', 'Rear Delt Machine', 'Pec Deck Reverse'],
    pattern: 'isolation',
    primaryMuscles: ['rear_delts'],
    secondaryMuscles: ['upper_back'],
    equipment: ['machine'],
    unit: 'kg',
    increment: PIN_STEP,
    repRange: [12, 20],
    cue: 'Arms nearly straight. Think about spreading the hands apart, not squeezing the blades.',
    usesBodyweight: false,
    bodyweightFactor: 1,
  },
  {
    id: 'cable-bicep-curl',
    name: 'Cable Bicep Curl',
    aliases: ['Cabel Bicep Curl', 'Cable Curl'],
    pattern: 'isolation',
    primaryMuscles: ['biceps'],
    secondaryMuscles: ['forearms'],
    equipment: ['cable'],
    unit: 'kg',
    increment: PIN_STEP,
    repRange: [10, 15],
    cue: 'Elbows pinned to the sides. The cable keeps tension at the top, so use it.',
    usesBodyweight: false,
    bodyweightFactor: 1,
  },

  /* ---------------- Wednesday: abs and biceps ---------------- */
  {
    id: 'machine-preacher-curl',
    name: 'Machine Preacher Curls',
    aliases: ['Preacher Curl Machine', 'Machine Preacher Curl'],
    pattern: 'isolation',
    primaryMuscles: ['biceps'],
    secondaryMuscles: [],
    equipment: ['machine'],
    unit: 'kg',
    increment: PIN_STEP,
    repRange: [10, 15],
    cue: 'The pad removes the cheat. Do not fight it by lifting the elbows.',
    usesBodyweight: false,
    bodyweightFactor: 1,
  },
  {
    id: 'strict-curl',
    name: 'Strict Curls',
    aliases: ['Strict Curl', 'Barbell Strict Curl'],
    pattern: 'isolation',
    primaryMuscles: ['biceps'],
    secondaryMuscles: ['forearms'],
    equipment: ['barbell'],
    unit: 'kg',
    increment: 1.25,
    repRange: [6, 10],
    cue: 'Back against a wall if there is one. No hip drive at all.',
    usesBodyweight: false,
    bodyweightFactor: 1,
  },
  {
    id: 'leg-raises',
    name: 'Leg Raises',
    aliases: ['Lying Leg Raise', 'Leg Raise'],
    pattern: 'core',
    primaryMuscles: ['abs'],
    secondaryMuscles: ['obliques'],
    equipment: ['bodyweight'],
    unit: 'reps',
    increment: 0,
    repRange: [12, 20],
    progressionLadder: ['leg-raises', 'hanging-leg-raises'],
    cue: 'Press the lower back into the floor. Stop before it arches.',
    usesBodyweight: true,
    // Reasoned from segment mass, not measured — legs only. See §7.
    bodyweightFactor: 0.3,
  },
  {
    id: 'machine-abs-crunch',
    name: 'Machine Abs Crunch',
    aliases: ['Ab Crunch Machine', 'Machine Crunch'],
    pattern: 'core',
    primaryMuscles: ['abs'],
    secondaryMuscles: [],
    equipment: ['machine'],
    unit: 'kg',
    increment: PIN_STEP,
    repRange: [10, 15],
    cue: 'Shorten the distance between ribs and hips. It is a curl, not a hip fold.',
    usesBodyweight: false,
    bodyweightFactor: 1,
  },
  {
    id: 'cable-crunch',
    name: 'Cable Crunch',
    aliases: ['Kneeling Cable Crunch', 'Rope Crunch'],
    pattern: 'core',
    primaryMuscles: ['abs'],
    secondaryMuscles: ['obliques'],
    equipment: ['cable'],
    unit: 'kg',
    increment: PIN_STEP,
    repRange: [10, 15],
    cue: 'Hips stay where they are. Pull the elbows toward the knees with the abs.',
    usesBodyweight: false,
    bodyweightFactor: 1,
  },

  /* ---------------- Thursday: chest, shoulders, triceps, supersetted ---------------- */
  {
    id: 'incline-pushups',
    name: 'Incline Pushups',
    aliases: ['Incline Push-ups', 'Hands-elevated Pushups'],
    pattern: 'horizontal_push',
    primaryMuscles: ['chest'],
    secondaryMuscles: ['front_delts', 'triceps'],
    equipment: ['bodyweight', 'bench'],
    unit: 'reps',
    increment: 0,
    repRange: [10, 20],
    progressionLadder: ['incline-pushups', 'pike-pushups', 'diamond-pushups'],
    cue: 'The higher the hands, the easier it is. Lower the hands as this gets easy.',
    usesBodyweight: true,
    // Reasoned, not measured, and the honest weak spot: this genuinely varies
    // with bench height, and one number is wrong at both ends. See §7.
    bodyweightFactor: 0.5,
  },
  {
    id: 'pike-pushups',
    name: 'Pike Pushups',
    aliases: ['Pike Push-ups'],
    pattern: 'vertical_push',
    primaryMuscles: ['front_delts'],
    secondaryMuscles: ['triceps', 'chest'],
    equipment: ['bodyweight'],
    unit: 'reps',
    increment: 0,
    repRange: [8, 15],
    progressionLadder: ['incline-pushups', 'pike-pushups', 'diamond-pushups'],
    cue: 'Hips high, head travels between the hands. This one is a shoulder press.',
    usesBodyweight: true,
    // Reasoned, not measured — torso vertical, most of the load on the shoulders. See §7.
    bodyweightFactor: 0.7,
  },
  {
    id: 'cable-chest-press-mid',
    name: 'Cable Chest Press (mid chest)',
    aliases: ['Cable Press Mid', 'Cable Chest Press'],
    pattern: 'horizontal_push',
    primaryMuscles: ['chest'],
    secondaryMuscles: ['front_delts', 'triceps'],
    equipment: ['cable'],
    unit: 'kg',
    increment: PIN_STEP,
    repRange: [10, 15],
    cue: 'Pulleys at chest height. Press straight out and squeeze at the midline.',
    usesBodyweight: false,
    bodyweightFactor: 1,
  },
  {
    id: 'cable-chest-press-low',
    name: 'Cable Chest Press (lower chest)',
    aliases: ['Cable Press Low', 'High-to-low Cable Press'],
    pattern: 'horizontal_push',
    primaryMuscles: ['chest'],
    secondaryMuscles: ['front_delts', 'triceps'],
    equipment: ['cable'],
    unit: 'kg',
    increment: PIN_STEP,
    repRange: [10, 15],
    cue: 'Pulleys high, press down and in toward the hips.',
    usesBodyweight: false,
    bodyweightFactor: 1,
  },
  {
    id: 'cable-chest-press-high',
    name: 'Cable Chest Press (upper chest)',
    aliases: ['Cable Press High', 'Low-to-high Cable Press'],
    pattern: 'horizontal_push',
    primaryMuscles: ['chest'],
    secondaryMuscles: ['front_delts', 'triceps'],
    equipment: ['cable'],
    unit: 'kg',
    increment: PIN_STEP,
    repRange: [10, 15],
    cue: 'Pulleys low, press up and in toward the collarbones.',
    usesBodyweight: false,
    bodyweightFactor: 1,
  },
  {
    id: 'tricep-overhead-extension',
    name: 'Tricep Overhead Extension',
    aliases: ['Tricep Overhead Extention', 'Overhead Tricep Extension'],
    pattern: 'isolation',
    primaryMuscles: ['triceps'],
    secondaryMuscles: [],
    equipment: ['cable'],
    unit: 'kg',
    increment: PIN_STEP,
    repRange: [10, 15],
    cue: 'Upper arms stay beside the ears. The stretch at the bottom is the point.',
    usesBodyweight: false,
    bodyweightFactor: 1,
  },

  /* ---------------- Friday: legs ---------------- */
  {
    id: 'barbell-squat',
    name: 'Barbell Squats',
    aliases: ['Barbell Squat', 'Back Squat', 'Squat'],
    pattern: 'squat',
    primaryMuscles: ['quads'],
    secondaryMuscles: ['glutes', 'lower_back', 'hamstrings'],
    equipment: ['barbell'],
    unit: 'kg',
    increment: 5,
    repRange: [5, 8],
    standardLift: 'squat',
    cue: 'Knees track over the toes. Depth first, load second.',
    usesBodyweight: false,
    bodyweightFactor: 1,
  },
  {
    id: 'leg-press',
    name: 'Leg Press',
    aliases: ['Machine Leg Press'],
    pattern: 'squat',
    primaryMuscles: ['quads'],
    secondaryMuscles: ['glutes'],
    equipment: ['machine'],
    unit: 'kg',
    increment: 5,
    repRange: [10, 15],
    cue: 'Do not let the lower back round off the pad at the bottom.',
    usesBodyweight: false,
    bodyweightFactor: 1,
  },
  {
    id: 'hamstring-curl',
    name: 'Hamstring Curl',
    aliases: ['Leg Curl', 'Lying Leg Curl', 'Seated Leg Curl'],
    pattern: 'isolation',
    primaryMuscles: ['hamstrings'],
    secondaryMuscles: ['calves'],
    equipment: ['machine'],
    unit: 'kg',
    increment: PIN_STEP,
    repRange: [10, 15],
    cue: 'The only hamstring work in the week. Control the lowering.',
    usesBodyweight: false,
    bodyweightFactor: 1,
  },
  {
    id: 'leg-extension',
    name: 'Leg Extension',
    aliases: ['Quad Extension'],
    pattern: 'isolation',
    primaryMuscles: ['quads'],
    secondaryMuscles: [],
    equipment: ['machine'],
    unit: 'kg',
    increment: PIN_STEP,
    repRange: [12, 15],
    cue: 'Pause at the top for a beat rather than swinging through.',
    usesBodyweight: false,
    bodyweightFactor: 1,
  },
  {
    id: 'barbell-calf-raise',
    name: 'Barbell Calf Raises',
    aliases: ['Barbell Calf Raise', 'Standing Calf Raise'],
    pattern: 'isolation',
    primaryMuscles: ['calves'],
    secondaryMuscles: [],
    equipment: ['barbell'],
    unit: 'kg',
    increment: 5,
    repRange: [10, 15],
    cue: 'Full stretch at the bottom, full contraction at the top. Slow, not bouncy.',
    usesBodyweight: false,
    bodyweightFactor: 1,
  },

  /* ---------------- Saturday: cardio and abs ---------------- */
  {
    id: 'hanging-leg-raises',
    name: 'Hanging Leg Raises',
    aliases: ['Hanging Leg Raise', 'Hanging Knee Raise'],
    pattern: 'core',
    primaryMuscles: ['abs'],
    secondaryMuscles: ['obliques', 'grip'],
    equipment: ['pullup_bar', 'bodyweight'],
    unit: 'reps',
    increment: 0,
    repRange: [8, 15],
    progressionLadder: ['leg-raises', 'hanging-leg-raises'],
    cue: 'Stop the swing before each rep. Curl the pelvis rather than just lifting the legs.',
    usesBodyweight: true,
    // Reasoned from segment mass, not measured — legs, with the trunk stabilising. See §7.
    bodyweightFactor: 0.35,
  },
  {
    id: 'treadmill-intervals',
    name: 'Treadmill Intervals',
    aliases: ['Treadmill', 'Walk Run Intervals', 'Cardio'],
    pattern: 'cardio',
    primaryMuscles: ['cardio'],
    secondaryMuscles: [],
    equipment: ['treadmill'],
    unit: 'time',
    increment: 0,
    repRange: [1, 1],
    cue: 'Five minutes walking, five minutes running, repeated. Walk in zone 2, run in zone 4.',
    usesBodyweight: false,
    bodyweightFactor: 1,
  },

  /* ---------------- Available for the Daily Quest and Instant Dungeons ---------------- */
  {
    id: 'pushups',
    name: 'Pushups',
    aliases: ['Push-ups', 'Push Ups'],
    pattern: 'horizontal_push',
    primaryMuscles: ['chest'],
    secondaryMuscles: ['triceps', 'front_delts'],
    equipment: ['bodyweight'],
    unit: 'reps',
    increment: 0,
    repRange: [10, 30],
    progressionLadder: ['incline-pushups', 'pushups', 'diamond-pushups'],
    cue: 'Body in one line from head to heels.',
    usesBodyweight: true,
    // The most commonly cited figure for a standard pushup (~64% of bodyweight),
    // but not independently verified against a primary source here — see §7.
    bodyweightFactor: 0.64,
  },
  {
    id: 'bodyweight-squat',
    name: 'Bodyweight Squats',
    aliases: ['Air Squat', 'Bodyweight Squat'],
    pattern: 'squat',
    primaryMuscles: ['quads'],
    secondaryMuscles: ['glutes'],
    equipment: ['bodyweight'],
    unit: 'reps',
    increment: 0,
    repRange: [15, 40],
    cue: 'Sit down between the heels. Full depth every rep.',
    usesBodyweight: true,
    // Reasoned, not measured — trunk plus most of the legs. See §7.
    bodyweightFactor: 0.65,
  },
  {
    id: 'situps',
    name: 'Sit-ups',
    aliases: ['Situps', 'Sit Ups'],
    pattern: 'core',
    primaryMuscles: ['abs'],
    secondaryMuscles: ['obliques'],
    equipment: ['bodyweight'],
    unit: 'reps',
    increment: 0,
    repRange: [15, 40],
    cue: 'Do not yank on the neck. Lead with the ribs.',
    usesBodyweight: true,
    // Reasoned, not measured — the trunk, not the whole body. See §7.
    bodyweightFactor: 0.45,
  },
]

/**
 * The six training days. Day numbers match `Date.prototype.getDay`, so Sunday
 * is 0 and is deliberately absent — Sunday is rest.
 *
 * Gate ranks here are starting values. Once there is history the real rank is
 * computed from planned tonnage and intensity by `gateDifficulty`.
 */
export const SEED_ROUTINES: readonly Routine[] = [
  {
    id: 'monday-cst',
    dayOfWeek: 1,
    name: 'CST Gate',
    gateRank: 'C',
    blocks: [
      { type: 'single', items: [{ exerciseId: 'incline-barbell-press', sets: 4, repRange: [5, 8], restSec: 180 }] },
      { type: 'single', items: [{ exerciseId: 'machine-shoulder-press', sets: 3, repRange: [8, 12], restSec: 120 }] },
      { type: 'single', items: [{ exerciseId: 'skullcrusher', sets: 3, repRange: [8, 12], restSec: 90 }] },
      { type: 'single', items: [{ exerciseId: 'cable-fly', sets: 3, repRange: [10, 15], restSec: 75 }] },
      { type: 'single', items: [{ exerciseId: 'machine-lateral-raise', sets: 3, repRange: [12, 20], restSec: 60 }] },
      { type: 'single', items: [{ exerciseId: 'front-raises', sets: 2, repRange: [12, 15], restSec: 60 }] },
      { type: 'single', items: [{ exerciseId: 'diamond-pushups', sets: 3, repRange: [8, 20], restSec: 90 }] },
    ],
  },
  {
    id: 'tuesday-back-biceps',
    dayOfWeek: 2,
    name: 'Back and Biceps Gate',
    gateRank: 'C',
    blocks: [
      { type: 'single', items: [{ exerciseId: 'one-arm-cable-lat-pulldown', sets: 3, repRange: [8, 12], restSec: 90 }] },
      { type: 'single', items: [{ exerciseId: 'pull-ups', sets: 4, repRange: [5, 12], restSec: 150 }] },
      { type: 'single', items: [{ exerciseId: 'dumbbell-row', sets: 3, repRange: [8, 12], restSec: 120 }] },
      { type: 'single', items: [{ exerciseId: 'cable-shrug', sets: 3, repRange: [10, 15], restSec: 75 }] },
      { type: 'single', items: [{ exerciseId: 'machine-reverse-fly', sets: 3, repRange: [12, 20], restSec: 60 }] },
      { type: 'single', items: [{ exerciseId: 'cable-bicep-curl', sets: 3, repRange: [10, 15], restSec: 60 }] },
    ],
  },
  {
    id: 'wednesday-abs-biceps',
    dayOfWeek: 3,
    name: 'Abs and Biceps Gate',
    gateRank: 'D',
    blocks: [
      { type: 'single', items: [{ exerciseId: 'machine-preacher-curl', sets: 3, repRange: [10, 15], restSec: 75 }] },
      { type: 'single', items: [{ exerciseId: 'cable-bicep-curl', sets: 3, repRange: [10, 15], restSec: 60 }] },
      { type: 'single', items: [{ exerciseId: 'strict-curl', sets: 3, repRange: [6, 10], restSec: 90 }] },
      { type: 'single', items: [{ exerciseId: 'leg-raises', sets: 3, repRange: [12, 20], restSec: 60 }] },
      { type: 'single', items: [{ exerciseId: 'machine-abs-crunch', sets: 3, repRange: [10, 15], restSec: 60 }] },
      { type: 'single', items: [{ exerciseId: 'cable-crunch', sets: 3, repRange: [10, 15], restSec: 60 }] },
    ],
  },
  {
    id: 'thursday-cst-supersets',
    dayOfWeek: 4,
    name: 'CST Gate (Supersets)',
    gateRank: 'C',
    // The `+` pairs in the brief are real supersets, performed alternating.
    blocks: [
      {
        type: 'superset',
        items: [
          { exerciseId: 'incline-pushups', sets: 3, repRange: [10, 20], restSec: 0 },
          { exerciseId: 'cable-chest-press-mid', sets: 3, repRange: [10, 15], restSec: 90 },
        ],
      },
      {
        type: 'superset',
        items: [
          { exerciseId: 'pike-pushups', sets: 3, repRange: [8, 15], restSec: 0 },
          { exerciseId: 'cable-chest-press-low', sets: 3, repRange: [10, 15], restSec: 90 },
        ],
      },
      {
        type: 'superset',
        items: [
          { exerciseId: 'diamond-pushups', sets: 3, repRange: [8, 20], restSec: 0 },
          { exerciseId: 'cable-chest-press-high', sets: 3, repRange: [10, 15], restSec: 90 },
        ],
      },
      { type: 'single', items: [{ exerciseId: 'machine-shoulder-press', sets: 3, repRange: [8, 12], restSec: 120 }] },
      { type: 'single', items: [{ exerciseId: 'tricep-overhead-extension', sets: 3, repRange: [10, 15], restSec: 75 }] },
    ],
  },
  {
    id: 'friday-legs',
    dayOfWeek: 5,
    name: 'Legs Gate',
    gateRank: 'B',
    blocks: [
      { type: 'single', items: [{ exerciseId: 'barbell-squat', sets: 4, repRange: [5, 8], restSec: 210 }] },
      { type: 'single', items: [{ exerciseId: 'leg-press', sets: 3, repRange: [10, 15], restSec: 150 }] },
      {
        type: 'superset',
        items: [
          { exerciseId: 'hamstring-curl', sets: 3, repRange: [10, 15], restSec: 0 },
          { exerciseId: 'leg-extension', sets: 3, repRange: [12, 15], restSec: 90 },
        ],
      },
      { type: 'single', items: [{ exerciseId: 'barbell-calf-raise', sets: 4, repRange: [10, 15], restSec: 75 }] },
    ],
  },
  {
    id: 'saturday-cardio-abs',
    dayOfWeek: 6,
    name: 'Cardio and Abs Gate',
    gateRank: 'D',
    blocks: [
      { type: 'single', items: [{ exerciseId: 'leg-raises', sets: 3, repRange: [12, 20], restSec: 60 }] },
      { type: 'single', items: [{ exerciseId: 'cable-crunch', sets: 3, repRange: [10, 15], restSec: 60 }] },
      { type: 'single', items: [{ exerciseId: 'hanging-leg-raises', sets: 3, repRange: [8, 15], restSec: 75 }] },
      { type: 'single', items: [{ exerciseId: 'treadmill-intervals', sets: 1, repRange: [1, 1], restSec: 0 }] },
    ],
  },
]

/** Lookup by id, for the many callers that resolve an exercise from a set log. */
export const SEED_EXERCISE_BY_ID: ReadonlyMap<string, Exercise> = new Map(
  SEED_EXERCISES.map((exercise) => [exercise.id, exercise]),
)

export function seedExercise(id: string): Exercise | undefined {
  return SEED_EXERCISE_BY_ID.get(id)
}

export function routineForDayOfWeek(dayOfWeek: number): Routine | undefined {
  return SEED_ROUTINES.find((routine) => routine.dayOfWeek === dayOfWeek)
}
